import type { Invoice, NewInvoice } from '@/db/database.service';
import { databaseService } from '@/db/database.service';
import { LocalAppService } from '@/services/local-app.service';

export interface InvoicesPort {
  getInvoices(): Promise<Invoice[]>;
  createInvoice(invoice: NewInvoice): Promise<Invoice>;
  updateInvoice(id: string, updates: Partial<Invoice>): Promise<Invoice>;
  deleteInvoice(id: string): Promise<void>;
}

export const invoicesAdapter: InvoicesPort = {
  getInvoices: async (): Promise<Invoice[]> => {
    try {
      const localApp = LocalAppService.getInstance?.();
      const isElectron = !!localApp?.getConfig?.().isElectron;
      if (isElectron) {
        const res: any = await localApp!.getInvoices();
        const invoices = res?.ok ? (res.data as Invoice[]) : (res as Invoice[]);
        // CRITICAL: Filter out deleted invoices at adapter level for Electron
        // This ensures deleted invoices never reach the UI, even if database query fails
        if (Array.isArray(invoices)) {
          return invoices.filter((inv: any) => {
            const deleted = inv?.deleted;
            return !deleted && deleted !== 1 && deleted !== '1' && deleted !== true;
          });
        }
        return invoices || [];
      }
    } catch (e) {
      // Fallback to cloud database if anything goes wrong
    }
    return await databaseService.getInvoices();
  },
  createInvoice: async (invoice: NewInvoice): Promise<Invoice> => {
    try {
      const localApp = LocalAppService.getInstance?.();
      const isElectron = !!localApp?.getConfig?.().isElectron;
      if (isElectron) {
        const nowIso = new Date().toISOString();
        const localPayload: any = {
          customer_id: invoice.customer_id,
          customer_name: invoice.customer_name,
          customer_phone: invoice.customer_phone,
          customer_address: invoice.customer_address,
          total: invoice.total,
          paid_amount: invoice.paid_amount ?? 0,
          status: invoice.status ?? 'معلق',
          invoice_date: nowIso,
          due_date: invoice.due_date,
          notes: invoice.notes,
          fabric_image_url: invoice.fabric_image_url,
          paid_at: (invoice as any).paid_at,
          // design details (optional)
          fabric_type: (invoice as any).fabric_type,
          fabric_source: (invoice as any).fabric_source,
          collar_type: (invoice as any).collar_type,
          chest_style: (invoice as any).chest_style,
          sleeve_end: (invoice as any).sleeve_end,
          bunija_type: (invoice as any).bunija_type,
          // customer measurements snapshot
          customer_measurements: (invoice as any).customer_measurements,
          // invoice_number will be generated by the database
        };
        const createdRes: any = await localApp!.createInvoice(localPayload);
        const created = createdRes?.ok ? createdRes.data : createdRes;
        return created as Invoice;
      }
    } catch (e) {
      // Fallback to cloud database
    }
    return await databaseService.createInvoice(invoice);
  },
  updateInvoice: async (id: string, updates: Partial<Invoice>): Promise<Invoice> => {
    try {
      const localApp = LocalAppService.getInstance?.();
      const isElectron = !!localApp?.getConfig?.().isElectron;
      if (isElectron) {
        const updatedRes: any = await localApp!.updateInvoice(id, updates);
        const updated = updatedRes?.ok ? updatedRes.data : updatedRes;
        return updated as Invoice;
      }
    } catch (e) {
      // Fallback to cloud database
    }
    return await databaseService.updateInvoice(id, updates);
  },
  deleteInvoice: async (id: string): Promise<void> => {
    try {
      const localApp = LocalAppService.getInstance?.();
      const isElectron = !!localApp?.getConfig?.().isElectron;
      if (isElectron) {
        const delRes: any = await localApp!.deleteInvoice(id);
        if (delRes?.ok === false) {
          throw new Error(delRes?.error || 'Failed to delete invoice');
        }
        return;
      }
    } catch (e) {
      // Fallback to cloud database
    }
    return await databaseService.deleteInvoice(id);
  },
};


